# Create .github/FUNDING.yml
github: rafaumeu # Replace with your GitHub username
# Replace with your PayPal.me link if you have one

# You can also add other funding platforms:
# ko_fi: yourname
# patreon: yourname
# open_collective: yourname
# liberapay: yourname
# issuehunt: yourname
# otechie: yourname
# lfx_crowdfunding: yourname
# community_bridge: yourname
