# Configuração do labeler
novato:
  - novato.c
  - "**/novato.c"

aventureiro:
  - aventureiro.c
  - "**/aventureiro.c"

mestre:
  - mestre.c
  - "**/mestre.c"

documentacao:
  - "**/*.md"
  - "docs/**/*"

workflow:
  - ".github/**/*"

build:
  - "**/Makefile"
  - "**/*.c"
  - "*.c"

beginner:
  - "src/**/*"
  - "include/**/*"
  - "tests/**/*"
  - "Makefile"

enhancement:
  - "src/**/*.c"
  - "include/**/*.h"

i18n:
  - "src/i18n.c"
  - "include/i18n.h"

bug-fix:
  - "src/interface.c"
  - "src/main.c"
