# Configuração do labeler
novato:
  - "novato.c"

aventureiro:
  - "aventureiro.c"

mestre:
  - "mestre.c"

documentacao:
  - "**/*.md"
  - "docs/**/*"

workflow:
  - ".github/**/*"

build:
  - "**/Makefile"
  - "**/*.c"
  - "*.c"
