name: C Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GCC and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make valgrind cppcheck

      - name: Compile
        run: |
          gcc -Wall -Wextra -o novato novato.c -lm

      - name: Static Analysis
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem ./

      - name: Memory Check
        run: |
          valgrind --leak-check=full ./novato
