name: Project Automation
on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  issue_opened:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/rafaumeu/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  issue_closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Mover para coluna "Concluído"
            // Adicione lógica específica aqui
